# Generated by Django 4.2.3 on 2023-07-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="produit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("categories", models.CharField(max_length=200)),
                ("brands", models.CharField(max_length=200)),
                ("nutriscore_score", models.IntegerField()),
                ("quantity", models.CharField(max_length=200)),
                ("nutriscore_grade", models.CharField(max_length=200)),
            ],
        ),
    ]
