# Generated by Django 4.2.3 on 2023-07-10 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produit",
            name="nutriscore_score",
            field=models.IntegerField(null=True),
        ),
    ]
