# Generated by Django 4.2.3 on 2023-07-10 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_alter_produit_nutriscore_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produit",
            name="quantity",
            field=models.CharField(max_length=5000),
        ),
    ]
