# Generated by Django 4.2.3 on 2023-07-10 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0005_alter_produit_nutriscore_score"),
    ]

    operations = [
        migrations.RemoveField(model_name="produit", name="categories",),
        migrations.RemoveField(model_name="produit", name="nutriscore_grade",),
        migrations.RemoveField(model_name="produit", name="nutriscore_score",),
        migrations.RemoveField(model_name="produit", name="quantity",),
    ]
