# Generated by Django 4.2.3 on 2023-07-10 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0006_remove_produit_categories_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produit",
            name="brands",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
