# Generated by Django 4.2.3 on 2023-07-10 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0008_alter_produit_brands"),
    ]

    operations = [
        migrations.AddField(
            model_name="produit",
            name="categories",
            field=models.CharField(default="", max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="produit",
            name="nutriscore_grade",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="produit",
            name="nutriscore_score",
            field=models.CharField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="produit",
            name="quantity",
            field=models.CharField(default="", max_length=5000),
            preserve_default=False,
        ),
    ]
