# Generated by Django 4.2.3 on 2023-07-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0009_produit_categories_produit_nutriscore_grade_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produit",
            name="categories",
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name="produit",
            name="nutriscore_grade",
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name="produit", name="nutriscore_score", field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="produit",
            name="quantity",
            field=models.TextField(max_length=5000),
        ),
    ]
