# Generated by Django 4.2.3 on 2023-07-10 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0010_alter_produit_categories_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produit",
            name="id",
            field=models.CharField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="produit",
            name="nutriscore_score",
            field=models.TextField(null=True),
        ),
    ]
