# Generated by Django 4.2.3 on 2023-07-10 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0011_alter_produit_id_alter_produit_nutriscore_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produit",
            name="nutriscore_grade",
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="produit",
            name="quantity",
            field=models.TextField(max_length=5000, null=True),
        ),
    ]
